use_frameworks!

platform :ios, '10.0'

target 'iOSCelebi_Example' do
  pod 'iOSCelebi', :path => '../'
  pod 'FBSDKLoginKit'

  target 'iOSCelebi_Tests' do
    inherit! :search_paths

    
  end
end
